### ISSUE TITLE
Add local file reading

### ISSUE THREAD

**Issue by smarticu5** [PaloAltoNetworks/rbac-police#4]
### Is your feature request related to a problem?

rbac-police requires a connection to the Kubernetes cluster. This is not always possible in a locked down environment. 

### Describe the solution you'd like

Additional functionality which allows rbac-police to process local manifest files (either in .json or .yaml). I propose this could be added using a --local-file flag to the collect command. 

### Describe alternatives you've considered

My current alternative is to create a new test cluster and apply existing RBAC to that, which is not the most reliable of offerings as there are occasional conflicts between default resources and what I'm adding.

**Comment by yuvalavra** [comment]
Done via #8, use `--local-dir <dir>` to run in offline mode. You can use [utils/get_cluster_data.sh](https://github.com/PaloAltoNetworks/rbac-police/blob/25dd22ad512ec33650a1cc650db7d4c633fd239c/utils/get_cluster_data.sh) to get the data needed for an offline run
